// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tokenswap/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # proto/tx/message
type MsgCreateSwapRequest struct {
	Creator        string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	BurnTxHash     string `protobuf:"bytes,2,opt,name=burnTxHash,proto3" json:"burnTxHash,omitempty"`
	EthereumSender string `protobuf:"bytes,3,opt,name=ethereumSender,proto3" json:"ethereumSender,omitempty"`
	Receiver       string `protobuf:"bytes,4,opt,name=receiver,proto3" json:"receiver,omitempty"`
	AmountEng      string `protobuf:"bytes,5,opt,name=amountEng,proto3" json:"amountEng,omitempty"`
	SignerAddr     string `protobuf:"bytes,6,opt,name=signerAddr,proto3" json:"signerAddr,omitempty"`
}

func (m *MsgCreateSwapRequest) Reset()         { *m = MsgCreateSwapRequest{} }
func (m *MsgCreateSwapRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCreateSwapRequest) ProtoMessage()    {}
func (*MsgCreateSwapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_93d21519151b16a6, []int{0}
}
func (m *MsgCreateSwapRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateSwapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateSwapRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateSwapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateSwapRequest.Merge(m, src)
}
func (m *MsgCreateSwapRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateSwapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateSwapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateSwapRequest proto.InternalMessageInfo

func (m *MsgCreateSwapRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateSwapRequest) GetBurnTxHash() string {
	if m != nil {
		return m.BurnTxHash
	}
	return ""
}

func (m *MsgCreateSwapRequest) GetEthereumSender() string {
	if m != nil {
		return m.EthereumSender
	}
	return ""
}

func (m *MsgCreateSwapRequest) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *MsgCreateSwapRequest) GetAmountEng() string {
	if m != nil {
		return m.AmountEng
	}
	return ""
}

func (m *MsgCreateSwapRequest) GetSignerAddr() string {
	if m != nil {
		return m.SignerAddr
	}
	return ""
}

type MsgCreateSwapRequestResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCreateSwapRequestResponse) Reset()         { *m = MsgCreateSwapRequestResponse{} }
func (m *MsgCreateSwapRequestResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateSwapRequestResponse) ProtoMessage()    {}
func (*MsgCreateSwapRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_93d21519151b16a6, []int{1}
}
func (m *MsgCreateSwapRequestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateSwapRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateSwapRequestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateSwapRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateSwapRequestResponse.Merge(m, src)
}
func (m *MsgCreateSwapRequestResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateSwapRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateSwapRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateSwapRequestResponse proto.InternalMessageInfo

func (m *MsgCreateSwapRequestResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgUpdateSwapRequest struct {
	Creator        string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id             uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	BurnTxHash     string `protobuf:"bytes,3,opt,name=burnTxHash,proto3" json:"burnTxHash,omitempty"`
	EthereumSender string `protobuf:"bytes,4,opt,name=ethereumSender,proto3" json:"ethereumSender,omitempty"`
	Receiver       string `protobuf:"bytes,5,opt,name=receiver,proto3" json:"receiver,omitempty"`
	AmountEng      string `protobuf:"bytes,6,opt,name=amountEng,proto3" json:"amountEng,omitempty"`
	SignerAddr     string `protobuf:"bytes,7,opt,name=signerAddr,proto3" json:"signerAddr,omitempty"`
}

func (m *MsgUpdateSwapRequest) Reset()         { *m = MsgUpdateSwapRequest{} }
func (m *MsgUpdateSwapRequest) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateSwapRequest) ProtoMessage()    {}
func (*MsgUpdateSwapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_93d21519151b16a6, []int{2}
}
func (m *MsgUpdateSwapRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateSwapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateSwapRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateSwapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateSwapRequest.Merge(m, src)
}
func (m *MsgUpdateSwapRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateSwapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateSwapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateSwapRequest proto.InternalMessageInfo

func (m *MsgUpdateSwapRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateSwapRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgUpdateSwapRequest) GetBurnTxHash() string {
	if m != nil {
		return m.BurnTxHash
	}
	return ""
}

func (m *MsgUpdateSwapRequest) GetEthereumSender() string {
	if m != nil {
		return m.EthereumSender
	}
	return ""
}

func (m *MsgUpdateSwapRequest) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *MsgUpdateSwapRequest) GetAmountEng() string {
	if m != nil {
		return m.AmountEng
	}
	return ""
}

func (m *MsgUpdateSwapRequest) GetSignerAddr() string {
	if m != nil {
		return m.SignerAddr
	}
	return ""
}

type MsgUpdateSwapRequestResponse struct {
}

func (m *MsgUpdateSwapRequestResponse) Reset()         { *m = MsgUpdateSwapRequestResponse{} }
func (m *MsgUpdateSwapRequestResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateSwapRequestResponse) ProtoMessage()    {}
func (*MsgUpdateSwapRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_93d21519151b16a6, []int{3}
}
func (m *MsgUpdateSwapRequestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateSwapRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateSwapRequestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateSwapRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateSwapRequestResponse.Merge(m, src)
}
func (m *MsgUpdateSwapRequestResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateSwapRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateSwapRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateSwapRequestResponse proto.InternalMessageInfo

type MsgDeleteSwapRequest struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgDeleteSwapRequest) Reset()         { *m = MsgDeleteSwapRequest{} }
func (m *MsgDeleteSwapRequest) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteSwapRequest) ProtoMessage()    {}
func (*MsgDeleteSwapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_93d21519151b16a6, []int{4}
}
func (m *MsgDeleteSwapRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteSwapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteSwapRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteSwapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteSwapRequest.Merge(m, src)
}
func (m *MsgDeleteSwapRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteSwapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteSwapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteSwapRequest proto.InternalMessageInfo

func (m *MsgDeleteSwapRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeleteSwapRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgDeleteSwapRequestResponse struct {
}

func (m *MsgDeleteSwapRequestResponse) Reset()         { *m = MsgDeleteSwapRequestResponse{} }
func (m *MsgDeleteSwapRequestResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteSwapRequestResponse) ProtoMessage()    {}
func (*MsgDeleteSwapRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_93d21519151b16a6, []int{5}
}
func (m *MsgDeleteSwapRequestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteSwapRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteSwapRequestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteSwapRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteSwapRequestResponse.Merge(m, src)
}
func (m *MsgDeleteSwapRequestResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteSwapRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteSwapRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteSwapRequestResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateSwapRequest)(nil), "hdachmh.swapmodule.tokenswap.MsgCreateSwapRequest")
	proto.RegisterType((*MsgCreateSwapRequestResponse)(nil), "hdachmh.swapmodule.tokenswap.MsgCreateSwapRequestResponse")
	proto.RegisterType((*MsgUpdateSwapRequest)(nil), "hdachmh.swapmodule.tokenswap.MsgUpdateSwapRequest")
	proto.RegisterType((*MsgUpdateSwapRequestResponse)(nil), "hdachmh.swapmodule.tokenswap.MsgUpdateSwapRequestResponse")
	proto.RegisterType((*MsgDeleteSwapRequest)(nil), "hdachmh.swapmodule.tokenswap.MsgDeleteSwapRequest")
	proto.RegisterType((*MsgDeleteSwapRequestResponse)(nil), "hdachmh.swapmodule.tokenswap.MsgDeleteSwapRequestResponse")
}

func init() { proto.RegisterFile("tokenswap/tx.proto", fileDescriptor_93d21519151b16a6) }

var fileDescriptor_93d21519151b16a6 = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xbd, 0xae, 0xd3, 0x30,
	0x14, 0xc7, 0x9b, 0xa4, 0xb7, 0x97, 0xeb, 0xe1, 0x4a, 0x58, 0x0c, 0x51, 0x55, 0x59, 0x28, 0x03,
	0x62, 0x69, 0x22, 0xca, 0xc6, 0xc4, 0xa7, 0x84, 0x84, 0xba, 0xa4, 0xb0, 0xb0, 0xa5, 0xf1, 0x51,
	0x1c, 0xd1, 0xc4, 0xc1, 0x76, 0x68, 0x99, 0x79, 0x01, 0x36, 0x5e, 0x89, 0xb1, 0x62, 0x62, 0x44,
	0xe9, 0x8b, 0xa0, 0x38, 0xa4, 0xad, 0xea, 0x7e, 0x84, 0x3b, 0xfa, 0x6f, 0x9f, 0x73, 0xfe, 0xe7,
	0x77, 0x8e, 0x8c, 0xb0, 0xe2, 0x9f, 0x20, 0x97, 0xcb, 0xa8, 0x08, 0xd4, 0xca, 0x2f, 0x04, 0x57,
	0x1c, 0x8f, 0x18, 0x8d, 0x62, 0x96, 0x31, 0xbf, 0x96, 0x33, 0x4e, 0xcb, 0x05, 0xf8, 0xdb, 0x67,
	0xde, 0x2f, 0x0b, 0x3d, 0x98, 0xca, 0xe4, 0x95, 0x80, 0x48, 0xc1, 0x6c, 0x19, 0x15, 0x21, 0x7c,
	0x2e, 0x41, 0x2a, 0xec, 0xa2, 0xeb, 0xb8, 0x16, 0xb9, 0x70, 0xad, 0x87, 0xd6, 0xe3, 0x9b, 0xb0,
	0x3d, 0x62, 0x82, 0xd0, 0xbc, 0x14, 0xf9, 0xfb, 0xd5, 0xdb, 0x48, 0x32, 0xd7, 0xd6, 0x97, 0x7b,
	0x0a, 0x7e, 0x84, 0x6e, 0x41, 0x31, 0x10, 0x50, 0x66, 0x33, 0xc8, 0x29, 0x08, 0xd7, 0xd1, 0x6f,
	0x0e, 0x54, 0x3c, 0x44, 0xf7, 0x04, 0xc4, 0x90, 0x7e, 0x01, 0xe1, 0xf6, 0xf5, 0x8b, 0xed, 0x19,
	0x8f, 0xd0, 0x4d, 0x94, 0xf1, 0x32, 0x57, 0x6f, 0xf2, 0xc4, 0xbd, 0xd2, 0x97, 0x3b, 0xa1, 0x76,
	0x20, 0xd3, 0x24, 0x07, 0xf1, 0x82, 0x52, 0xe1, 0x0e, 0x1a, 0x07, 0x3b, 0xc5, 0xf3, 0xd1, 0xe8,
	0x58, 0x4f, 0x21, 0xc8, 0x82, 0xe7, 0x12, 0xf0, 0x2d, 0xb2, 0x53, 0xaa, 0xdb, 0xea, 0x87, 0x76,
	0x4a, 0xbd, 0xaa, 0x81, 0xf0, 0xa1, 0xa0, 0x9d, 0x21, 0x34, 0x29, 0xec, 0x36, 0xc5, 0x01, 0x14,
	0xa7, 0x03, 0x94, 0xfe, 0x45, 0x28, 0x57, 0xe7, 0xa0, 0x0c, 0xce, 0x43, 0xb9, 0x36, 0xa0, 0x10,
	0x0d, 0xc5, 0xe8, 0xb1, 0x85, 0xe2, 0x3d, 0xd7, 0x0c, 0x5e, 0xc3, 0x02, 0xee, 0xc8, 0xe0, 0x5f,
	0x05, 0x23, 0x43, 0x5b, 0x61, 0xf2, 0xc3, 0x41, 0xce, 0x54, 0x26, 0xf8, 0x9b, 0x85, 0xee, 0x9b,
	0x0b, 0x37, 0xf1, 0xcf, 0x2d, 0xaa, 0x7f, 0x6c, 0xa0, 0xc3, 0x67, 0xff, 0x1f, 0xb3, 0x5d, 0x82,
	0xda, 0x85, 0x39, 0xf1, 0xcb, 0x2e, 0x8c, 0x98, 0x0e, 0x2e, 0x4e, 0x52, 0xd7, 0x2e, 0x4c, 0xe6,
	0x97, 0x5d, 0x18, 0x31, 0x1d, 0x5c, 0x9c, 0x9c, 0xcc, 0xcb, 0x77, 0x3f, 0x2b, 0x62, 0xad, 0x2b,
	0x62, 0xfd, 0xa9, 0x88, 0xf5, 0x7d, 0x43, 0x7a, 0xeb, 0x0d, 0xe9, 0xfd, 0xde, 0x90, 0xde, 0xc7,
	0x27, 0x49, 0xaa, 0x58, 0x39, 0xf7, 0x63, 0x9e, 0x05, 0x75, 0xfe, 0x31, 0xcb, 0x58, 0x50, 0x27,
	0x1c, 0x37, 0x15, 0x82, 0x55, 0xb0, 0xf7, 0xe7, 0x7c, 0x2d, 0x40, 0xce, 0x07, 0xfa, 0xdf, 0x79,
	0xfa, 0x37, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x36, 0xf7, 0x13, 0x8d, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// this line is used by starport scaffolding # proto/tx/rpc
	CreateSwapRequest(ctx context.Context, in *MsgCreateSwapRequest, opts ...grpc.CallOption) (*MsgCreateSwapRequestResponse, error)
	UpdateSwapRequest(ctx context.Context, in *MsgUpdateSwapRequest, opts ...grpc.CallOption) (*MsgUpdateSwapRequestResponse, error)
	DeleteSwapRequest(ctx context.Context, in *MsgDeleteSwapRequest, opts ...grpc.CallOption) (*MsgDeleteSwapRequestResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateSwapRequest(ctx context.Context, in *MsgCreateSwapRequest, opts ...grpc.CallOption) (*MsgCreateSwapRequestResponse, error) {
	out := new(MsgCreateSwapRequestResponse)
	err := c.cc.Invoke(ctx, "/hdachmh.swapmodule.tokenswap.Msg/CreateSwapRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateSwapRequest(ctx context.Context, in *MsgUpdateSwapRequest, opts ...grpc.CallOption) (*MsgUpdateSwapRequestResponse, error) {
	out := new(MsgUpdateSwapRequestResponse)
	err := c.cc.Invoke(ctx, "/hdachmh.swapmodule.tokenswap.Msg/UpdateSwapRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteSwapRequest(ctx context.Context, in *MsgDeleteSwapRequest, opts ...grpc.CallOption) (*MsgDeleteSwapRequestResponse, error) {
	out := new(MsgDeleteSwapRequestResponse)
	err := c.cc.Invoke(ctx, "/hdachmh.swapmodule.tokenswap.Msg/DeleteSwapRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// this line is used by starport scaffolding # proto/tx/rpc
	CreateSwapRequest(context.Context, *MsgCreateSwapRequest) (*MsgCreateSwapRequestResponse, error)
	UpdateSwapRequest(context.Context, *MsgUpdateSwapRequest) (*MsgUpdateSwapRequestResponse, error)
	DeleteSwapRequest(context.Context, *MsgDeleteSwapRequest) (*MsgDeleteSwapRequestResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateSwapRequest(ctx context.Context, req *MsgCreateSwapRequest) (*MsgCreateSwapRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSwapRequest not implemented")
}
func (*UnimplementedMsgServer) UpdateSwapRequest(ctx context.Context, req *MsgUpdateSwapRequest) (*MsgUpdateSwapRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSwapRequest not implemented")
}
func (*UnimplementedMsgServer) DeleteSwapRequest(ctx context.Context, req *MsgDeleteSwapRequest) (*MsgDeleteSwapRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSwapRequest not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateSwapRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateSwapRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hdachmh.swapmodule.tokenswap.Msg/CreateSwapRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateSwapRequest(ctx, req.(*MsgCreateSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateSwapRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateSwapRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hdachmh.swapmodule.tokenswap.Msg/UpdateSwapRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateSwapRequest(ctx, req.(*MsgUpdateSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteSwapRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteSwapRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hdachmh.swapmodule.tokenswap.Msg/DeleteSwapRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteSwapRequest(ctx, req.(*MsgDeleteSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hdachmh.swapmodule.tokenswap.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSwapRequest",
			Handler:    _Msg_CreateSwapRequest_Handler,
		},
		{
			MethodName: "UpdateSwapRequest",
			Handler:    _Msg_UpdateSwapRequest_Handler,
		},
		{
			MethodName: "DeleteSwapRequest",
			Handler:    _Msg_DeleteSwapRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tokenswap/tx.proto",
}

func (m *MsgCreateSwapRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateSwapRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateSwapRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SignerAddr) > 0 {
		i -= len(m.SignerAddr)
		copy(dAtA[i:], m.SignerAddr)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SignerAddr)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.AmountEng) > 0 {
		i -= len(m.AmountEng)
		copy(dAtA[i:], m.AmountEng)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AmountEng)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.EthereumSender) > 0 {
		i -= len(m.EthereumSender)
		copy(dAtA[i:], m.EthereumSender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EthereumSender)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BurnTxHash) > 0 {
		i -= len(m.BurnTxHash)
		copy(dAtA[i:], m.BurnTxHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BurnTxHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateSwapRequestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateSwapRequestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateSwapRequestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateSwapRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateSwapRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateSwapRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SignerAddr) > 0 {
		i -= len(m.SignerAddr)
		copy(dAtA[i:], m.SignerAddr)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SignerAddr)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.AmountEng) > 0 {
		i -= len(m.AmountEng)
		copy(dAtA[i:], m.AmountEng)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AmountEng)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.EthereumSender) > 0 {
		i -= len(m.EthereumSender)
		copy(dAtA[i:], m.EthereumSender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EthereumSender)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.BurnTxHash) > 0 {
		i -= len(m.BurnTxHash)
		copy(dAtA[i:], m.BurnTxHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BurnTxHash)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateSwapRequestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateSwapRequestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateSwapRequestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteSwapRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteSwapRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteSwapRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteSwapRequestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteSwapRequestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteSwapRequestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateSwapRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.BurnTxHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.EthereumSender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AmountEng)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SignerAddr)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateSwapRequestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgUpdateSwapRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	l = len(m.BurnTxHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.EthereumSender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AmountEng)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SignerAddr)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateSwapRequestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteSwapRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgDeleteSwapRequestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateSwapRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateSwapRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateSwapRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnTxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BurnTxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthereumSender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EthereumSender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountEng", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AmountEng = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignerAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateSwapRequestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateSwapRequestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateSwapRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateSwapRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateSwapRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateSwapRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnTxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BurnTxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthereumSender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EthereumSender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountEng", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AmountEng = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignerAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateSwapRequestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateSwapRequestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateSwapRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteSwapRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteSwapRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteSwapRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteSwapRequestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteSwapRequestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteSwapRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
